import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import axios from 'axios';

export default function Home() {
  const [search_query, SetSearchQuery] = useState();
  const [searchBarFocus, SetSearchBarFocus] = useState(false);
  const [products, setProducts] = useState([]);
  const SearchqueryChange = (e) => {
    SetSearchQuery(e.target.value)
  }

  const CancelSearch = (e) => {
    SetSearchBarFocus(false)
  }

  useEffect(() => {
    axios.post('https://api.matspar.se/slug',
      {
        slug : "kategori",
        query : {"q" : "cocacola"}
      },
      {
        headers : {
          'content-type': 'application/json'
        }
      }
      )
    .then(response => {
      console.log(response.data);
    });
  },[])
  return (
    <>
      <Head>
        <title>Matspar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          {searchBarFocus ? <></> :
          <Image 
            src="/submenu.svg"
            alt="product image"
            width={22}
            height={15}
            priority
          />
          }
          <div className={styles.searchPart}>
            <Image
              src="/Search.png"
              alt="product image"
              width={20}
              height={20}
              priority
            />
            <input className={styles.searchbar} placeholder='Search Product' value={search_query} onFocus={(e) => {SetSearchBarFocus(true)}} onChange={SearchqueryChange}/>
            <Image
              src="/Search.png"
              alt="product image"
              width={20}
              height={20}
              priority
              onClick={(e) => {CancelSearch()}}
            />
          </div>
        </div>
        
        {searchBarFocus ? 
          search_query ?
            <>
              <div className={styles.searchHeader}>
                <p>Popular searches</p>
              </div>
              <div className={styles.searchResult}>
                <div className={styles.searchResultItem}>
                  <p>Coca cola</p>
                  <Image
                    src="/Search.png"
                    width={15}
                    height={15}
                    priority
                  />
                </div>
                <div className={styles.searchResultItem}>
                  <p>Coca Cola Zero</p>
                  <Image
                    src="/Search.png"
                    width={15}
                    height={15}
                    priority
                  />
                </div>
              </div>
            </>
            : 
            <>
              <div className={styles.searchHeader}>
                <p>Recent searches</p>
                <p>Clear all</p>
              </div>
              <div className={styles.searchResult}>
                <div className={styles.searchResultItem}>
                  <p>Coca cola</p>
                  <Image
                    src="/close.png"
                    alt="product image"
                    width={15}
                    height={15}
                    priority
                  />
                </div>
                <div className={styles.searchResultItem}>
                  <p>Coca cola</p>
                  <Image
                    src="/close.png"
                    alt="product image"
                    width={15}
                    height={15}
                    priority
                  />
                </div>
              </div>
            </>
        
          :
          <div>
            <p className={styles.title}>
              Find your favorite products now.
            </p>
            <div className={styles.container}>
              <div className={styles.tab_wrap}>
                <input type="radio" id="tab1" name="tabGroup1" className={styles.tab} />
                <label htmlFor="tab1">Trendy foods</label>

                <input type="radio" id="tab2" name="tabGroup1" className={styles.tab} />
                <label htmlFor="tab2">Bread</label>

                <input type="radio" id="tab3" name="tabGroup1" className={styles.tab} />
                <label htmlFor="tab3">Milk</label>

                <input type="radio" id="tab4" name="tabGroup1" className={styles.tab} />
                <label htmlFor="tab4">Egg</label>

                <div className={styles.tab__content}>
                  <div className={styles.tabContent_container}>
                    <div className={styles.productItem}>
                      <div className={styles.productLogo}>
                        <Image
                          src="/juice.png"
                          alt="product image"
                          width={28}
                          height={98}
                          priority
                        />
                      </div>
                      <p className={styles.productName}>Product Name</p>
                      <p className={styles.productBrand}>Brand</p>
                      <p className={styles.productPrice}>$799</p>
                    </div>
                    <div className={styles.productItem}>
                      <div className={styles.productLogo}>
                        <Image
                          src="/juice.png"
                          alt="product image"
                          width={28}
                          height={98}
                          priority
                        />
                      </div>
                      <p className={styles.productName}>Product Name</p>
                      <p className={styles.productBrand}>Brand</p>
                      <p className={styles.productPrice}>$799</p>
                    </div>
                    <div className={styles.productItem}>
                      <div className={styles.productLogo}>
                        <Image
                          src="/juice.png"
                          alt="product image"
                          width={28}
                          height={98}
                          priority
                        />
                      </div>
                      <p className={styles.productName}>Product Name</p>
                      <p className={styles.productBrand}>Brand</p>
                      <p className={styles.productPrice}>$799</p>
                    </div>
                    <div className={styles.productItem}>
                      <div className={styles.productLogo}>
                        <Image
                          src="/juice.png"
                          alt="product image"
                          width={28}
                          height={98}
                          priority
                        />
                      </div>
                      <p className={styles.productName}>Product Name</p>
                      <p className={styles.productBrand}>Brand</p>
                      <p className={styles.productPrice}>$799</p>
                    </div>
                  </div>
                  
                </div>

                <div className={styles.tab__content}>
                  <h3>Medium Section</h3>
                </div>

                <div className={styles.tab__content}>
                  <h3>Long Section</h3>
                </div>

                <div className={styles.tab__content}>
                  <h3>Short Section</h3>
                </div>

              </div>
            </div>
          </div>
        }
      </main>
    </>
  )
}
