import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import axios from 'axios';


export default function Home() {
  const [search_query, SetSearchQuery] = useState();
  const [searchBarFocus, SetSearchBarFocus] = useState(false);
  // const [products, setProducts] = useState([]);
  const [recent_query, SetRecentQuery] = useState(()=>new Set());
  const [popular_query, SetPopularQuery] = useState([]);

  const category = ["cocacola", "bread", "milk", "egg"]
  const SearchqueryChange = (e) => {
    SetSearchQuery(e.target.value)
    axios.get(`https://cors-anywhere.herokuapp.com/https://api.matspar.se/autocomplete?query=${e.target.value}`)
    .then(res => {
      console.log(res.data.suggestions)
      SetPopularQuery(res.data.suggestions)
    })
  }

  const CancelSearch = (e) => {
    SetSearchBarFocus(false)
    SetSearchQuery('')
  }
  //remove each recent search record
  const RemoveRecentQuery = (q) => {
    SetRecentQuery(prev => {
      const next = new Set(prev);
      next.delete(q);
      return next;
    });
  }
  const myLoader = ({ src, width, quality }) => {
    return `https://d1ax460061ulao.cloudfront.net/140x150/${src[0]}/${src[1]}/${src}.jpg`
  }

  const searchProduct = (query) => {
    console.log("-----------", query)
    SetRecentQuery(prev => new Set(prev).add(query))
    setProducts(FetchData(query))
    console.log(">>>>>>>>>", recent_query)
    SetSearchBarFocus(false)
    SetSearchQuery('')
  }

  const FetchData = async (Squery) => {
    axios.post('https://cors-anywhere.herokuapp.com/https://api.matspar.se/slug',
      {
        slug : "kategori",
        query : {"q" : Squery}
      },
      {
        headers : {
          'Access-Control-Allow-Origin': '*',
          'content-type': 'application/json',
          // 'origin' : window.location.protocol + '//' + window.location.host
        }
      }
      )
    .then(response => {
      console.log(response.data.payload.products)
      return response.data.payload.products; 
    });
  }
  
  function ItemList(query){
    const products = FetchData(query)
    console.log("----------",products)
    return(
      <div className={styles.tab__content}>
        <div className={styles.tabContent_container}>
          {/* {products.map((product, index)=>
            <div className={styles.productItem} key={index}>
              <div className={styles.productLogo}>
                <Image
                  loader={myLoader}
                  src={product.image}
                  alt="product image"
                  width="0"
                  height="0"
                  style={{ width: 'auto', height: 'auto', maxHeight : '150px'}}
                  // priority
                />
              </div>
              <p className={styles.productName}>{product.name}</p>
              <p className={styles.productBrand}>{product.brand}</p>
              <p className={styles.productPrice}>${product.price}</p>
            </div>
          )} */}
        </div>
      </div>
    )
  }

  return (
    <>
      <Head>
        <title>Matspar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          {searchBarFocus ? <></> :
          <Image 
            src="/submenu.svg"
            alt="product image"
            width={22}
            height={15}
            priority
          />
          }
          <div className={styles.searchPart}>
            <Image
              src="/Search.png"
              alt="product image"
              width={20}
              height={20}
              priority
              onClick={(e)=>{
                searchProduct(search_query)
              }}
            />
            <input className={styles.searchbar} placeholder='Search Product' value={search_query} onFocus={(e) => {SetSearchBarFocus(true)}} onChange={SearchqueryChange}/>
            {searchBarFocus ?
              <Image
                src="/close.png"
                alt="product image"
                width={20}
                height={20}
                priority
                onClick={(e) => {CancelSearch()}}
              />
              :
              <></>
            }
          </div>
        </div>
        
        {searchBarFocus ? 
          search_query ?
            <>
              <div className={styles.searchHeader}>
                <p>Popular searches</p>
              </div>
              <div className={styles.searchResult}>
                {popular_query.length > 0 ? 
                  popular_query.map((suggestion, index) => 
                  <div className={styles.searchResultItem} key={index}>
                    <p>{suggestion.text}</p>
                    <Image
                      src="/Search.png"
                      alt='search Icon'
                      width={15}
                      height={15}
                      priority
                      onClick={(e)=>{
                        searchProduct(suggestion.text)
                      }}
                    />
                  </div>
                  )
                  :
                  <></>
                }
              </div>
            </>
            : 
            <>
              <div className={styles.searchHeader}>
                <p>Recent searches</p>
                {recent_query? 
                  <p onClick={(e)=>{
                    SetRecentQuery(prev => new Set(prev).clear())
                  }}>
                    Clear all
                  </p>
                  : <></>}
              </div>
              <div className={styles.searchResult}>
              {recent_query ?
                Array.from(recent_query).map((rec_query, index)=>
                  <div className={styles.searchResultItem} key={index}>
                    <p>{rec_query}</p>
                    <Image
                      src="/close.png"
                      alt="product image"
                      width={15}
                      height={15}
                      priority
                      onClick={(e)=>{
                        RemoveRecentQuery(rec_query)
                      }}
                    />
                  </div>
                )
                :
                <></>
              }
              </div>
            </>
        
          :
          <div>
            <p className={styles.title}>
              Find your favorite products now.
            </p>
            <div className={styles.container}>
              <div className={styles.tab_wrap}>
                <input type="radio" id="tab1" name="category" className={styles.tab}/>
                <label htmlFor="tab1">Trendy foods</label>

                <input type="radio" id="tab2" name="category" className={styles.tab}/>
                <label htmlFor="tab2">Bread</label>

                <input type="radio" id="tab3" name="category" className={styles.tab}/>
                <label htmlFor="tab3">Milk</label>

                <input type="radio" id="tab4" name="category" className={styles.tab}/>
                <label htmlFor="tab4">Egg</label>

                {/* <div className={styles.tab__content}>
                  <div className={styles.tabContent_container}>
                    {products.map((product, index)=>
                      <div className={styles.productItem} key={index}>
                        <div className={styles.productLogo}>
                          <Image
                            loader={myLoader}
                            src={product.image}
                            alt="product image"
                            width="0"
                            height="0"
                            style={{ width: 'auto', height: 'auto', maxHeight : '150px'}}
                            // priority
                          />
                        </div>
                        <p className={styles.productName}>{product.name}</p>
                        <p className={styles.productBrand}>{product.brand}</p>
                        <p className={styles.productPrice}>${product.price}</p>
                      </div>
                    )}
                  </div>
                </div> */}
                <ItemList query={"cocacola"} />

                <div className={styles.tab__content}>
                  <h3>Medium Section</h3>
                </div>

                <div className={styles.tab__content}>
                  <h3>Long Section</h3>
                </div>

                <div className={styles.tab__content}>
                  <h3>Short Section</h3>
                </div>

              </div>
            </div>
          </div>
        }
      </main>
    </>
  )
}
