import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import axios from 'axios';


export default function Home() {
  const [search_query, SetSearchQuery] = useState();
  const [searchBarFocus, SetSearchBarFocus] = useState(false);
  const [products, setProducts] = useState([]);
  const [recent_query, SetRecentQuery] = useState(()=>new Set());
  const [popular_query, SetPopularQuery] = useState([]);
  const [category, setCategory] = useState("");
  const [loading, setloading] = useState(false);
  const [searchState, setSearchState] = useState(true)
  const SearchqueryChange = (e) => {
    SetSearchQuery(e.target.value)
    axios.get(`/api/search_suggestion?query=${e.target.value}`)
    .then(res => {
      console.log(res.data.suggestions)
      SetPopularQuery(res.data.suggestions)
    })
  }

  const CancelSearch = (e) => {
    SetSearchBarFocus(false)
    SetSearchQuery('')
    setCategory('')
    FetchData('')
    document.getElementById('search_part').style.width = "60%"
  }
  //remove each recent search record
  const RemoveRecentQuery = (q) => {
    SetRecentQuery(prev => {
      const next = new Set(prev);
      next.delete(q);
      return next;
    });
  }
  const myLoader = ({ src, width, quality }) => {
    return `https://d1ax460061ulao.cloudfront.net/140x150/${src[0]}/${src[1]}/${src}.jpg`
  }

  const searchProduct = (query) => {
    SetRecentQuery(prev => new Set(prev).add(query))
    SetSearchQuery('')
    FetchData(query)
  }

  const FetchData = async (Squery) => {
    setProducts([])
    setSearchState(false)
    setloading(true)
    axios.post("/api/getproducts", {
      Squery: Squery
    })
    .then((res) => {
      console.log(res.data.products)
      setProducts(res.data.products)
      setloading(false)
    })
  }
  
  useEffect(()=>{
    SetSearchBarFocus(false)
  },[])
  useEffect(()=>{
    FetchData(category)
  },[category])

  return (
    <>
      <Head>
        <title>Matspar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          {searchBarFocus ? <></> :
          <Image 
            src="/submenu.svg"
            alt="product image"
            width={22}
            height={15}
            priority
          />
          }
          <div id='search_part' className={styles.searchPart}>
            <Image
              src="/Search.png"
              alt="product image"
              width={20}
              height={20}
              priority
              onClick={(e)=>{
                searchProduct(search_query)
              }}
            />
            <input 
              className={styles.searchbar} 
              placeholder='Search Product' 
              value={search_query} 
              onFocus={(e) => {
                SetSearchBarFocus(true); 
                setSearchState(true);
                document.getElementById('search_part').style.width = "100%"
                }
              }
              onChange={SearchqueryChange}/>
            {searchBarFocus ?
              <Image
                src="/close.png"
                alt="product image"
                width={20}
                height={20}
                priority
                onClick={(e) => {CancelSearch()}}
              />
              :
              <></>
            }
          </div>
        </div>
        {searchBarFocus? 
          searchState?
            search_query ?
              <>
                <div className={styles.searchHeader}>
                  <p>Popular searches</p>
                </div>
                <div className={styles.searchResult}>
                  {popular_query.length > 0 ? 
                    popular_query.map((suggestion, index) => 
                    <div className={styles.searchResultItem} key={index}>
                      <p>{suggestion.text}</p>
                      <Image
                        src="/Search.png"
                        alt='search Icon'
                        width={15}
                        height={15}
                        priority
                        onClick={(e)=>{
                          searchProduct(suggestion.text)
                        }}
                      />
                    </div>
                    )
                    :
                    <></>
                  }
                </div>
              </>
              : 
              <>
                <div className={styles.searchHeader}>
                  <p>Recent searches</p>
                  {recent_query? 
                    <p onClick={(e)=>{
                      SetRecentQuery(prev => new Set(prev).clear())
                    }}>
                      Clear all
                    </p>
                    : <></>}
                </div>
                <div className={styles.searchResult}>
                {recent_query ?
                  Array.from(recent_query).map((rec_query, index)=>
                    <div className={styles.searchResultItem} key={index}>
                      <p onClick={(e) => {
                        searchProduct(rec_query)
                      }}>{rec_query}</p>
                      <Image
                        src="/close.png"
                        alt="product image"
                        width={15}
                        height={15}
                        priority
                        onClick={(e)=>{
                          RemoveRecentQuery(rec_query)
                        }}
                      />
                    </div>
                  )
                  :
                  <></>
                }
                </div>
              </>
            :
            <></>
          :
            <div>
              <p className={styles.title}>
                Find your favorite products now.
              </p>
              <div className={styles.container} >
                <div className={styles.tab_wrap}>
                  <input type="radio" id="tab1" name="category" className={styles.tab} value={""} checked={category == ""} onChange={(e) => {setCategory(e.target.value)}}/>
                  <label htmlFor="tab1">Trendy foods</label>
                  <input type="radio" id="tab2" name="category" className={styles.tab} value={"bread"} checked={category == "bread"} onChange={(e) => {setCategory(e.target.value)}}/>
                  <label htmlFor="tab2">Bread</label>
                  <input type="radio" id="tab3" name="category" className={styles.tab} value={"milk"} checked={category == "milk"} onChange={(e) => {setCategory(e.target.value)}}/>
                  <label htmlFor="tab3">Milk</label>
                  <input type="radio" id="tab4" name="category" className={styles.tab} value={"egg"} checked={category == "egg"} onChange={(e) => {setCategory(e.target.value)}}/>
                  <label htmlFor="tab4">Egg</label>
                </div>
              </div>
            </div>
            }
            {searchState?
              <></>
              :
              loading ? 
              <div className={styles.loader}></div> 
              :
              <div className={styles.tab__content}>
                <div className={styles.tabContent_container}>
                  {
                    products.length > 0 ?
                      products.map((product, index)=>
                        <div className={styles.productItem} key={index}>
                          <div style={{padding : '10px'}}>
                            <div className={styles.productLogo}>
                              {product.image == ""?
                                <Image
                                  src="/matspar.jpg"
                                  alt="product image"
                                  width="0"
                                  height="0"
                                  style={{ width: 'auto', height: 'auto', minWidth : '100px', maxHeight : '150px'}}
                                />
                                :
                                <Image
                                  loader={myLoader}
                                  src={product.image}
                                  alt="product image"
                                  width="0"
                                  height="0"
                                  style={{ width: 'auto', height: 'auto', maxHeight : '150px'}}
                                />
                              }
                              
                            </div>
                            <p className={styles.productName}>{product.name}</p>
                            <p className={styles.productBrand}>{product.brand}</p>
                            <p className={styles.productPrice}>${product.price}</p>
                          </div>
                        </div>
                      )
                    :
                    <div>
                      <p>No result</p>
                    </div>
                    }
                </div>
              </div>
            }
          {/* </> */}
        {/* } */}
      </main>
    </>
  )
}
